name: FCS Wordpress Deploy Via SFTP

run-name: FCS Wordpress Deploy To Server 🚀
on:
  push:
    branches:
      - production
      - master

jobs:
  send_deploying:
    name: Send Telegram Message When Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Check if FPT_DIR_PATH is set
        id: check_secret
        run: echo "FPT_DIR_PATH=${{ secrets.FPT_DIR_PATH }}" > $GITHUB_ENV
        continue-on-error: true # Continue even if the secret is not set

      - name: Set environment variable for secret presence
        id: set_env
        run: |
          if [ -z "${{ secrets.FPT_DIR_PATH }}" ]; then
            echo "SECRET_NOT_SET=true" >> $GITHUB_ENV
          else
            echo "SECRET_NOT_SET=false" >> $GITHUB_ENV
          fi

      - name: Send Telegram Message When Deploying
        if: env.SECRET_NOT_SET == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: -1002034905977
          token: 6611988217:AAERCNw3lNbdpABmMztQudQXBuPcp1jsKdk
          format: html
          message: |
            <i><code>${{ secrets.FPT_DIR_PATH }}</code><b> Website Deploying... 🚀</b></i>

            <b>Details:</b>
            Project name 💻: ${{ github.repository }}
            Project link 🔎: https://${{ secrets.FPT_DIR_PATH }}

  web-deploy-via-sfpt:
    name: 🚀 Deploy Website To Production

    runs-on: ubuntu-latest

    needs: send_deploying

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FPT_SERVER}}
          username: ${{secrets.FPT_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./src/
          server-dir: /${{secrets.FPT_DIR_PATH}}/

  notification-to-telegram:
    runs-on: ubuntu-latest
    needs: [send_deploying, web-deploy-via-sfpt]
    if: |
      always() && 
      (needs.web-deploy-via-sfpt.result == 'success')
    steps:
      - name: Telegram Notification
        uses: appleboy/telegram-action@master

        with:
          to: -1002034905977
          token: 6611988217:AAERCNw3lNbdpABmMztQudQXBuPcp1jsKdk
          format: html
          message: |
            <i><code>${{secrets.FPT_DIR_PATH}}</code><b> Website Deployed ✅</b></i>

            <b>Details:</b>
            Project name 💻: ${{ github.repository }}
            Project link 🔎: https://github.com/${{ github.repository }}
            See new changes: https://${{secrets.FPT_DIR_PATH}}
